GRANT EXECUTE ON GRUPPO1 TO ANONYMOUS;
GRANT EXECUTE ON GRUPPO2 TO ANONYMOUS;
GRANT EXECUTE ON GRUPPO3 TO ANONYMOUS;
GRANT EXECUTE ON GRUPPO4 TO ANONYMOUS;
GRANT EXECUTE ON INSERIMENTODATI TO ANONYMOUS;
GRANT EXECUTE ON GUI TO ANONYMOUS;